name: Build GraalVM JRE Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [17, 21, 22]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl grep sed

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check latest GraalVM version for Java ${{ matrix.java_version }}
        id: check_version
        run: |
          JAVA_VERSION=${{ matrix.java_version }}
          RELEASE_NOTES_URL="https://docs.oracle.com/en/graalvm/jdk/$JAVA_VERSION/docs/release-notes/"
          LATEST_VERSION=$(curl -s "$RELEASE_NOTES_URL" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | head -n 1)
          echo "Latest GraalVM version for Java $JAVA_VERSION: $LATEST_VERSION"
          
          if [ -z "$LATEST_VERSION" ]; then
            echo "Version not found" 
            exit 1
          fi
          
          EXISTING_VERSION=$(docker pull "ghcr.io/${{ github.repository }}:$JAVA_VERSION-$LATEST_VERSION" || echo "not found")
          if [ "$EXISTING_VERSION" != "not found" ]; then
            echo "Version $LATEST_VERSION for Java $JAVA_VERSION already exists."
            echo "new_version=false" >> $GITHUB_ENV
          else
            echo "New version detected for Java $JAVA_VERSION: $LATEST_VERSION"
            echo "new_version=true" >> $GITHUB_ENV
            echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
            echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.new_version == 'true'
        run: |
          docker build --build-arg GRAALVM_VERSION=$LATEST_VERSION --build-arg JAVA_VERSION=${{ matrix.java_version }} -t "ghcr.io/${{ github.repository }}:${{ matrix.java_version }}-$LATEST_VERSION" .
          docker push "ghcr.io/${{ github.repository }}:${{ matrix.java_version }}-$LATEST_VERSION"
